### PR TITLE
Support $^ macro

### PR DESCRIPTION
**Pull request by illiliti**
See also: https://www.austingroupbugs.net/view.php?id=1520

---
TODO:

* [x] tests
* [x] docs/readme

### CODE REVIEW

**Comment by rmyorston** [comment]
I've hacked on this a bit: [0001-Add-internal-macro-as-an-extension.txt](https://github.com/rmyorston/pdpmake/files/8928406/0001-Add-internal-macro-as-an-extension.txt).

Please try it.

**Comment by illiliti** [comment]
Is it just me or pdpmake can't run its own tests _anymore_? Running `./make test` will always skip non-posix tests. Can you reproduce?

**Comment by rmyorston** [comment]
Tests work for me. The default build with extensions disabled skips the non-POSIX tests, but when extensions are enabled it's fine.

**Comment by illiliti** [comment]
I compiled pdpmake with -DENABLE_FEATURE_MAKE_EXTENSIONS=1 and tests are still being skipped. Note that if i do `gmake test` or `bmake test`, non-posix tests will work, but if i do `./make test`, they won't work. Weird...

**Comment by rmyorston** [comment]
The ```runtest``` script detects whether extensions are present or not by seeing what the binary does when presented with a makefile containing ```VAR := value```. Does your pdpmake binary handle that without error?

**Comment by illiliti** [comment]
For some reason it fails with: `-:1: invalid macro assignment`

**Comment by illiliti** [comment]
> I've hacked on this a bit: [0001-Add-internal-macro-as-an-extension.txt](https://github.com/rmyorston/pdpmake/files/8928406/0001-Add-internal-macro-as-an-extension.txt).

Applied, thanks!

**Comment by rmyorston** [comment]
Patch applied, thanks!

**Pull request closed without merging**
