### PR TITLE
Implement special target PHONY

### PR DESCRIPTION
**Pull request by illiliti**
See also: https://www.austingroupbugs.net/view.php?id=523

---
TODO:

* [x] tests
* [x] docs/readme

### CODE REVIEW

**Comment by illiliti** [comment]
This is probably completely wrong, but it's a start.

**Comment by rmyorston** [comment]
Here's what I've come up with: [0001-Add-support-for-.PHONY-special-target.txt](https://github.com/rmyorston/pdpmake/files/8948561/0001-Add-support-for-.PHONY-special-target.txt).

- Adjust to new conditional compilation scheme
- Use a flag to indicate a phony target rather than search prerequisites every time
- Ensure ```-t``` doesn't touch phony targets
- Don't remove phony targets on interrupt

Give it a try.

**Comment by rmyorston** [comment]
Revised patch: [0001v2-Add-support-for-.PHONY-special-target.txt](https://github.com/rmyorston/pdpmake/files/8952742/0001v2-Add-support-for-.PHONY-special-target.txt)

- Respect runtime POSIX mode setting
- Simplify test
- Fix error check in ```touch()```

**Comment by illiliti** [comment]
Thanks for working on this. Applied.

**Comment by rmyorston** [comment]
We now have ```.PHONY```. Thank you for you efforts.

**Pull request closed without merging**
